kind: ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kata-operator
subjects:
- kind: ServiceAccount
  name: kata-operator
  namespace: kata-operator
roleRef:
  kind: ClusterRole 
  name: kata-operator
  apiGroup: rbac.authorization.k8s.io
