kind: ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kata-label-node-rb
subjects:
- kind: ServiceAccount
  name: kata-label-node
  namespace: kata-operator
roleRef:
  kind: ClusterRole 
  name: node-labeler
  apiGroup: rbac.authorization.k8s.io
